name: food_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  dots_indicator: ^3.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  http: ^0.13.3
  intl: ^0.17.0
  google_maps_flutter: ^2.1.2
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/