name: food_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  dots_indicator: ^3.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  http: ^0.13.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/